(defun main()
    (let ((n (read))
          (alice 0)
          (bob 0)
          (lst nil))
        (dotimes (i n)
            (push (read) lst))
        (setq lst (sort lst #'>))
        (dotimes (i n)
            (if (evenp i)
                (incf alice (pop lst))
                (incf bob (pop lst))))
        (format t "~A~%" (- alice bob))))

(main)